# Generated by Django 4.2.3 on 2023-07-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
